version: "3.7"
services:

  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: MonsterShop
    restart: unless-stopped

  monstershop:
    image: matthijz98/monstershop:latest
    container_name: HapMapDjango
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --no-input && gunicorn monstershop.wsgi --bind 0.0.0.0:8001 --workers=2"
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - 8001:8001

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data:
