# Generated by Django 3.0.2 on 2020-02-17 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_street_name', models.CharField(max_length=256)),
                ('address_company_name', models.CharField(max_length=128)),
                ('address_house_nr', models.CharField(max_length=10)),
                ('address_region', models.CharField(max_length=128)),
                ('address_phone', models.IntegerField()),
                ('address_zip_code', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField()),
                ('order_required_date', models.DateTimeField()),
                ('order_completed_date', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('invoice_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_address', to='order_management.Address')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_tracking_code', models.CharField(max_length=128)),
                ('shipment_date', models.DateTimeField()),
                ('shipment_of_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_management.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipper_name', models.CharField(max_length=128)),
                ('shipper_tracking_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_amount_included', models.FloatField()),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_management.Shipment')),
                ('shipment_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.Product')),
            ],
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_shipper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_management.Shipper'),
        ),
        migrations.AddField(
            model_name='order',
            name='schiping_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_management.Shipper'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipping_address', to='order_management.Address'),
        ),
        migrations.AddField(
            model_name='address',
            name='address_county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_management.Country'),
        ),
        migrations.AddField(
            model_name='address',
            name='address_from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
