# Generated by Django 3.0.2 on 2020-04-28 21:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_place_name',
            field=models.CharField(default='null', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_address', to='order_management.Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 21, 50, 4, 239934, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_required_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='schiping_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order_management.Shipper'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipping_address', to='order_management.Address'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order_details_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
