# Generated by Django 3.0.2 on 2020-04-29 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_created_at', models.DateTimeField(auto_created=True)),
                ('product_name', models.CharField(max_length=512)),
                ('product_description', models.TextField()),
                ('product_min_order_amount', models.FloatField(default=0)),
                ('product_max_order_amount', models.FloatField(blank=True, null=True)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_field_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img_alt_text', models.CharField(max_length=64)),
                ('product_img_img', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_img', to=settings.FILER_IMAGE_MODEL)),
                ('product_img_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFieldDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.Product')),
                ('product_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.ProductField')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category_name', models.CharField(max_length=128)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='product_management.ProductCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_brand_created_at', models.DateTimeField(auto_created=True)),
                ('product_brand_name', models.CharField(max_length=128)),
                ('product_brand_updated_at', models.DateTimeField(auto_now=True)),
                ('product_brand_img', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_brand_img', to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_management.ProductBrand'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.ProductCategory'),
        ),
    ]
