# Generated by Django 3.0.2 on 2020-02-17 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=512)),
                ('product_description', models.TextField()),
                ('product_min_order_amount', models.FloatField()),
                ('product_max_order_amount', models.FloatField()),
                ('product_reorder_level', models.FloatField()),
                ('product_out_of_stock_date', models.DateTimeField()),
                ('product_created_at', models.DateTimeField()),
                ('product_updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ProductField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_field_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img_name', models.CharField(max_length=128)),
                ('product_img_alt_text', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ProductFieldDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.Product')),
                ('product_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.ProductField')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.ProductCategory'),
        ),
    ]
