# Generated by Django 3.0.2 on 2020-02-20 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimg',
            name='product_img_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product_management.Product'),
            preserve_default=False,
        ),
    ]
