# Generated by Django 3.0.2 on 2020-02-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0002_productimg_product_img_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimg',
            name='product_img_img',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
