# Generated by Django 3.0.2 on 2020-04-08 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0006_product_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_out_of_stock_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_reorder_level',
        ),
    ]
