# Generated by Django 3.0.2 on 2020-05-03 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_in_order_order_producer_order_id', models.CharField(blank=True, max_length=128, null=True)),
                ('buy_in_order_order_total_ammount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('buy_in_order_order_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer_name', models.CharField(max_length=128)),
                ('producer_email', models.EmailField(max_length=254)),
                ('producer_phone', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loction_name', models.CharField(max_length=64)),
                ('location_in_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_management.Warehouse')),
                ('sub_loction_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='stock_management.location')),
            ],
        ),
        migrations.CreateModel(
            name='BuyInOrderReceivement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_in_order_receivement_ammount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_in_order_receivement_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('buy_in_order_receivement_buy_in_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_management.BuyInOrder')),
                ('buy_in_order_receivement_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.Product')),
                ('buy_in_order_receivement_received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuyInOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_in_oder_detail_ammount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_in_oder_detail_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_in_oder_detail_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('buy_in_oder_detail_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('buy_in_oder_detail_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.Product')),
            ],
        ),
        migrations.AddField(
            model_name='buyinorder',
            name='buy_in_order_order_producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_management.Producer'),
        ),
    ]
